# Generated by Django 3.2.6 on 2021-11-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iris_API', '0002_alter_iris_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
