# Generated by Django 3.2.6 on 2021-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iris_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iris_in_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SepalLengthCm', models.FloatField()),
                ('SepalWidthCm', models.FloatField()),
                ('PetalLengthCm', models.FloatField()),
                ('PetalWidthCm', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Iris_model',
        ),
    ]
