# Generated by Django 3.2.6 on 2021-11-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iris_app', '0002_auto_20211117_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris_in_model',
            name='PetalLengthCm',
            field=models.FloatField(verbose_name='Petal Length Cm'),
        ),
        migrations.AlterField(
            model_name='iris_in_model',
            name='PetalWidthCm',
            field=models.FloatField(verbose_name='Petal Width Cm'),
        ),
        migrations.AlterField(
            model_name='iris_in_model',
            name='SepalLengthCm',
            field=models.FloatField(verbose_name='Sepal Length Cm'),
        ),
        migrations.AlterField(
            model_name='iris_in_model',
            name='SepalWidthCm',
            field=models.FloatField(verbose_name='Sepal Width Cm'),
        ),
    ]
